CREATE DATABASE IF NOT EXISTS openai;
CREATE DATABASE IF NOT EXISTS azure;
CREATE DATABASE IF NOT EXISTS ollama;
CREATE DATABASE IF NOT EXISTS library;

\c library;

CREATE TABLE IF NOT EXISTS books (
    id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    isbn VARCHAR(13) UNIQUE,
    published_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

